'use strict'
module.exports = {
    IncorrectArrayDeclarationInSortLibConstructor: require('./IncorrectArrayDeclarationInSortLibConstructor'),
    IncorrectArrayInAddElementInSortedArray: require('./IncorrectArrayInAddElementInSortedArray'),
    IncorrectArrayInSetterArray: require('./IncorrectArrayInSetterArray'),
    IncorrectArgumentInIndexSetter: require('./IncorrectArgumentInIndexSetter'),
    IncorrectStatusInSetter: require('./IncorrectStatusInSetter'),
    IncorrectStatusParameterInBucketSort: require('./IncorrectArrayParameterInBucketSort'),
    IncorrectParameterInGRA: require('./IncorrectParameterInGRA'),
    IncorrectArrayParameterInFindBestElements : require('./IncorrectArrayParameterInFindBestElements'),
    IncorrectArrayParameterInFindWortsElements : require('./IncorrectArrayParameterInFindWorstElements'),
    IncorrectArrayParameterInSortObjectArray : require('./IncorrectArrayParameterInSortObjectArray'),
    IncorrectPropertyInSortObjectArray : require('./IncorrectPropertyInSortObjectArray'),
    IncorrectArrayParameterInFindBestInObjectArray : require('./IncorrectArrayParameterInFindBestInObjectArray'),
    IncorrectPropertyParameterInFindBestInObjectArray : require('./IncorrectPropertyParameterInFindBestInObjectArray'),
    IncorrectArrayParameterInFindWorstInObjectArray : require('./IncorrectArrayParameterInFindWorstInObjectArray'),
    IncorrectPropertyParameterInFindWorstInObjectArray : require('./IncorrectPropertyParameterInFindWorstInObjectArray'),
    IncorrectCountParameterInFindWorstInObjectArray : require('./IncorrectCountParameterInFindWorstInObjectArray'),
    IncorrectArrayParameterInBucketSort : require('./IncorrectArrayParameterInBucketSort'),   
    IncorrectElementInFindElementInSortedArray : require('./IncorrectElementInFindElementInSortedArray'),
    IncorrectArrayParameterInFindElementInSortedArray : require('./IncorrectArrayParameterInFindElementInSortedArray'),
    IncorrectArrayParameterInAddElementInSortedObjectArrayByProperty : require('./IncorrectArrayParameterInAddElementInSortedObjectArrayByProperty'),
    IncorrectPropertyParameterInAddElementInSortedObjectArrayByProperty : require('./IncorrectPropertyParameterInAddElementInSortedObjectArrayByProperty'),
    IncorrectElementInAddElementInSortedObjectArrayByProperty : require('./IncorrectElementInAddElementInSortedObjectArrayByProperty'),
    IncorrectLengthInGRSA : require('./IncorrectLengthInGRSA'),
    IncorrectWordSizeInGRSA : require('./IncorrectWordSizeInGRSA'),
    IncorrectArrayInFindElementsInSortedObjectArray : require('./IncorrectArrayInFindElementsInSortedObjectArray'),
    IncorrectPropertyParameterInFindElementsInSortedObjectArray : require('./IncorrectPropertyParameterInFindElementsInSortedObjectArray'),
    IncorrectElementParameterInFindElementsInSortedObjectArray : require('./IncorrectElementParameterInFindElementsInSortedObjectArray'),
    IncorrectArrayInFilterWithValidator: require('./IncorrectArrayInFilterWithValidator'),
    IncorrectArgumentOfCallbackInFilterWithValidator: require('./IncorrectArgumentOfCallbackInFilterWithValidator'),
    IncorrectArrayInRemoveElementFromSortedArray: require('./IncorrectArrayInRemoveElementFromSortedArray'),
    IncorrectElementParameterInRemoveElementFromSortedArray: require('./IncorrectElementInRemoveElementFromSortedArray'),
    IncorrectArrayInRemoveElementFromSortedObjectArray: require('./IncorrectArrayInRemoveElementFromSortedObjectArray'),
    IncorrectPropertyParameterInRemoveElementFromSortedObjectArray: require('./IncorrectPropertyParameterInRemoveElementFromSortedObjectArray'),
    IncorrectElementParameterInRemoveElementFromSortedObjectArray: require('./IncorrectElementParameterInRemoveElementFromSortedObjectArray'),
    IncorrectModeParameterInRemoveElementFromSortedObjectArray: require('./IncorrectModeParameterInRemoveElementInSortedObjectArray'),
         
}